# Generated by Django 3.1.4 on 2021-01-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210110_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogs',
            field=models.ManyToManyField(blank=True, related_name='_blog_blogs_+', to='blog.Blog'),
        ),
    ]
