# Generated by Django 3.0.7 on 2020-06-27 10:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='isim')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=30, verbose_name='Telefon Numarası')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='İş ortağının adı:')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Ortak hakkında bilgi')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Referansın adı:')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Referans hakkında bilgi')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Hizmetin adı:')),
                ('font', models.CharField(choices=[('icofont-computer', 'bilgisayar'), ('icofont-chart-bar-graph', 'grafik'), ('icofont-image', 'resim'), ('icofont-settings', 'ayar'), ('icofont-earth', 'dünya'), ('icofont-tasks-alt', 'alt görev')], max_length=50)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Servis hakkında bilgi')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('icon', models.ImageField(upload_to='setting/', verbose_name='İcon')),
                ('image', models.ImageField(upload_to='setting/', verbose_name='Ana sayfadaki büyük resim')),
                ('youtube_url', models.URLField(verbose_name='anasayfadaki URL adresi')),
                ('header', models.CharField(max_length=150, verbose_name='ana sayfadaki resim üstündeki başlık')),
                ('content', models.CharField(max_length=150, verbose_name='ana sayfadaki resim üsütündeki içerik')),
                ('description', models.CharField(max_length=150, verbose_name="Google'da çıkacak olan yazı")),
                ('keywords', models.CharField(max_length=150, verbose_name="Google'da aramalarda çıkabilmek için gerekli anahtar kelimler")),
                ('about', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Çözüm adı:')),
                ('font', models.CharField(choices=[('icofont-computer', 'bilgisayar'), ('icofont-chart-bar-graph', 'grafik'), ('icofont-image', 'resim'), ('icofont-settings', 'ayar'), ('icofont-earth', 'dünya'), ('icofont-tasks-alt', 'alt görev')], max_length=50)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Çözüm hakkında bilgi')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresse', models.CharField(max_length=150, verbose_name='adres')),
                ('member', models.ManyToManyField(to='home.Member')),
            ],
        ),
    ]
