# Generated by Django 3.0.7 on 2020-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_youtube_url',
            field=models.URLField(default=1, verbose_name="Hakkımızda ile ilgili olan youtube URL'i "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='adresse',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='copyright_name',
            field=models.CharField(default='Sofistech', max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='get_startted',
            field=models.CharField(default='Get Started', max_length=50, verbose_name='Nabvardaki get_started'),
        ),
        migrations.AddField(
            model_name='setting',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='skype_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='content',
            field=models.CharField(blank=True, max_length=150, verbose_name='ana sayfadaki resim üsütündeki içerik'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='header',
            field=models.CharField(blank=True, max_length=150, verbose_name='ana sayfadaki resim üstündeki başlık'),
        ),
    ]
