# Generated by Django 3.0.7 on 2020-06-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200627_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Hakkımızda kısmında çıkacak olan resim'),
            preserve_default=False,
        ),
    ]
