# Generated by Django 3.0.7 on 2020-06-27 12:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_setting_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='hakkımızda başlığı')),
                ('sub_content', models.CharField(max_length=250, verbose_name='hakkımızda alt metin')),
                ('content', ckeditor.fields.RichTextField(verbose_name='içerik')),
                ('about_image', models.ImageField(upload_to='', verbose_name='Hakkımızda kısmında çıkacak olan resim')),
                ('about_youtube_url', models.URLField(verbose_name="Hakkımızda ile ilgili olan youtube URL'i ")),
            ],
        ),
        migrations.RemoveField(
            model_name='setting',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='about_youtube_url',
        ),
    ]
