# Generated by Django 3.0.7 on 2020-06-27 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200627_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='font',
            field=models.CharField(choices=[('icofont-computer', 'bilgisayar'), ('icofont-chart-bar-graph', 'grafik'), ('icofont-image', 'resim'), ('icofont-settings', 'ayar'), ('icofont-earth', 'dünya'), ('icofont-tasks-alt', 'alt görev'), ('icofont-award', 'ödül'), ('icofont-clock-time', 'saat'), ('icofont-document-folder', 'dosya')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solution',
            name='font',
            field=models.CharField(choices=[('icofont-computer', 'bilgisayar'), ('icofont-chart-bar-graph', 'grafik'), ('icofont-image', 'resim'), ('icofont-settings', 'ayar'), ('icofont-earth', 'dünya'), ('icofont-tasks-alt', 'alt görev'), ('icofont-award', 'ödül'), ('icofont-clock-time', 'saat'), ('icofont-document-folder', 'dosya')], max_length=50),
        ),
        migrations.CreateModel(
            name='AboutLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='açıklama')),
                ('font', models.CharField(choices=[('icofont-computer', 'bilgisayar'), ('icofont-chart-bar-graph', 'grafik'), ('icofont-image', 'resim'), ('icofont-settings', 'ayar'), ('icofont-earth', 'dünya'), ('icofont-tasks-alt', 'alt görev'), ('icofont-award', 'ödül'), ('icofont-clock-time', 'saat'), ('icofont-document-folder', 'dosya')], max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.About')),
            ],
        ),
    ]
