# Generated by Django 3.0.7 on 2020-06-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200627_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Vizyon başlığı')),
                ('content', models.CharField(max_length=150, verbose_name='içerik')),
                ('about_image', models.ImageField(upload_to='', verbose_name='resim')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutlogo',
            name='font',
            field=models.CharField(choices=[('icofont-computer', 'bilgisayar'), ('icofont-chart-bar-graph', 'grafik'), ('icofont-image', 'resim'), ('icofont-settings', 'ayar'), ('icofont-earth', 'dünya'), ('icofont-tasks-alt', 'alt görev'), ('icofont-award', 'ödül'), ('icofont-clock-time', 'saat'), ('icofont-document-folder', 'dosya'), ('icofont-simple-smile', 'gülücük'), ('ri-brush-4-line', 'mission'), ('ri-movie-2-line', 'film şeridi'), ('ri-calendar-check-line', 'takvim')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='font',
            field=models.CharField(choices=[('icofont-computer', 'bilgisayar'), ('icofont-chart-bar-graph', 'grafik'), ('icofont-image', 'resim'), ('icofont-settings', 'ayar'), ('icofont-earth', 'dünya'), ('icofont-tasks-alt', 'alt görev'), ('icofont-award', 'ödül'), ('icofont-clock-time', 'saat'), ('icofont-document-folder', 'dosya'), ('icofont-simple-smile', 'gülücük'), ('ri-brush-4-line', 'mission'), ('ri-movie-2-line', 'film şeridi'), ('ri-calendar-check-line', 'takvim')], max_length=50),
        ),
        migrations.AlterField(
            model_name='solution',
            name='font',
            field=models.CharField(choices=[('icofont-computer', 'bilgisayar'), ('icofont-chart-bar-graph', 'grafik'), ('icofont-image', 'resim'), ('icofont-settings', 'ayar'), ('icofont-earth', 'dünya'), ('icofont-tasks-alt', 'alt görev'), ('icofont-award', 'ödül'), ('icofont-clock-time', 'saat'), ('icofont-document-folder', 'dosya'), ('icofont-simple-smile', 'gülücük'), ('ri-brush-4-line', 'mission'), ('ri-movie-2-line', 'film şeridi'), ('ri-calendar-check-line', 'takvim')], max_length=50),
        ),
    ]
