# Generated by Django 3.0.7 on 2020-06-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200627_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='content',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='slug',
        ),
        migrations.AlterField(
            model_name='mission',
            name='font',
            field=models.CharField(choices=[('ri-brush-4-line', 'mission'), ('ri-movie-2-line', 'film şeridi'), ('ri-calendar-check-line', 'takvim')], max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(max_length=50, verbose_name='İş ortağının adı:'),
        ),
    ]
