# Generated by Django 3.0.7 on 2020-06-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200627_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='featers',
            field=models.BooleanField(default=False),
        ),
    ]
