# Generated by Django 3.0.7 on 2020-06-27 14:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200627_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Başlık:')),
                ('font', models.CharField(choices=[('icofont-computer', 'bilgisayar'), ('icofont-chart-bar-graph', 'grafik'), ('icofont-image', 'resim'), ('icofont-settings', 'ayar'), ('icofont-earth', 'dünya'), ('icofont-tasks-alt', 'alt görev'), ('icofont-award', 'ödül'), ('icofont-clock-time', 'saat'), ('icofont-document-folder', 'dosya'), ('icofont-simple-smile', 'gülücük'), ('ri-brush-4-line', 'mission'), ('ri-movie-2-line', 'film şeridi'), ('ri-calendar-check-line', 'takvim')], max_length=50)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Servis hakkında bilgi')),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='featers',
            new_name='features',
        ),
    ]
