# Generated by Django 3.0.7 on 2020-06-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200627_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Başlık:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='font',
            field=models.CharField(choices=[('ri-gps-line', 'gps'), ('ri-body-scan-line', 'body'), ('ri-sun-line', 'güneş'), ('ri-store-line', 'dükkan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='feature',
            name='font_title',
            field=models.CharField(max_length=50, verbose_name='Font Başlık'),
        ),
    ]
