# Generated by Django 3.0.7 on 2020-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_feature_sub_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='testimonials',
            field=models.BooleanField(default=False, verbose_name='Müşteri yorumlarının sergilenmesi için tıklayınız'),
        ),
    ]
