# Generated by Django 3.0.7 on 2020-06-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_setting_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Arka plan resmi')),
                ('title', models.CharField(max_length=50, verbose_name='Müşteri adı')),
                ('sub_title', models.CharField(max_length=50, verbose_name='Müşteri Ünvanı')),
                ('content', models.CharField(max_length=150, verbose_name='Müşteri Yorumu')),
            ],
        ),
    ]
