# Generated by Django 3.0.7 on 2020-06-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200628_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Şirket tipi')),
            ],
        ),
        migrations.AlterField(
            model_name='reference',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.CompanyType'),
        ),
    ]
