# Generated by Django 3.0.7 on 2020-06-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200628_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='teams',
            field=models.BooleanField(default=False, verbose_name='Sofistech ekibinin segilenmesi için tıklayınız.'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='testimonials',
            field=models.BooleanField(default=False, verbose_name='Müşteri yorumlarının sergilenmesi için tıklayınız.'),
        ),
    ]
