# Generated by Django 3.0.7 on 2020-06-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200628_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profil resmi'),
        ),
        migrations.AddField(
            model_name='member',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='job',
            field=models.CharField(default=1, max_length=50, verbose_name='ünvan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
