# Generated by Django 3.0.7 on 2020-06-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20200628_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.AddField(
            model_name='service',
            name='service_or_not',
            field=models.BooleanField(default=False, verbose_name='Hizmet ise tıklanacak değilse Tıklanmayacak'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='get_startted',
            field=models.CharField(default='Get Started', max_length=50, verbose_name='Navbardaki get_started'),
        ),
    ]
