# Generated by Django 3.0.7 on 2020-06-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200628_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default=1, max_length=150, verbose_name="Google'da çıkacak olan yazı"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='keywords',
            field=models.CharField(default=1, max_length=150, verbose_name="Google'da aramalarda çıkabilmek için gerekli anahtar kelimler"),
            preserve_default=False,
        ),
    ]
