# Generated by Django 3.0.7 on 2020-06-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Sitede gösterilsin mi'),
        ),
        migrations.AddField(
            model_name='service',
            name='home_content',
            field=models.CharField(default='Kısa Açıklama', max_length=250),
        ),
    ]
