# Generated by Django 3.0.7 on 2020-06-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20200629_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Hakkımızda', 'verbose_name_plural': 'Hakkımızdakiler'},
        ),
        migrations.AlterModelOptions(
            name='aboutlogo',
            options={'verbose_name': 'Hakkımızdada Bulunan Font', 'verbose_name_plural': 'Hakkımızdada Bulunan Fontlar'},
        ),
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name': 'Şirket Tipi', 'verbose_name_plural': 'Şirket Tipleri'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'İletişim', 'verbose_name_plural': 'İletişim Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Gelen Mesaj', 'verbose_name_plural': 'Gelen Mesajlar'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Ekstra Özellikler', 'verbose_name_plural': 'Özellikler'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Sofistech Üye', 'verbose_name_plural': 'Sofistech Üyeleri'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Vizyon', 'verbose_name_plural': 'Vizyonlar'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'İş Ortağı', 'verbose_name_plural': 'İş Ortakları'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Referans', 'verbose_name_plural': 'Referanslar'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Hizmet ve Çözüm', 'verbose_name_plural': 'Hizmet ve Çözümlerimiz'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Müşteri Görüşü', 'verbose_name_plural': 'Müşteri Görüşleri'},
        ),
    ]
