# Generated by Django 3.1.4 on 2020-12-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200629_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='software',
            field=models.BooleanField(default=False, verbose_name='Yazılım Hizmetleri için tıklanacal'),
        ),
    ]
