# Generated by Django 3.1.4 on 2021-01-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_service_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='software',
            field=models.BooleanField(default=False, verbose_name='Seo Başlıkları için tıklanacak'),
        ),
    ]
