# Generated by Django 3.1.5 on 2021-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_setting_whatsapp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.ImageField(default='', upload_to='setting/', verbose_name='logo'),
        ),
    ]
