# Generated by Django 3.1.5 on 2021-02-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_setting_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(default='Sofistech', upload_to='setting/', verbose_name='logo'),
        ),
    ]
